Get some practice with numpy:

https://numpy.org/doc/2.1/user/absolute_beginners.html

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Create a 1D NumPy array containing the numbers from 1 to 10.

Create a 1D array with 20 evenly spaced numbers between 0 and 1.

In [5]:
# write code here
arr_10=np.arange(1,11)
arr_20=np.linspace(0,1,20)
print(arr_10)
print(arr_20)


[ 1  2  3  4  5  6  7  8  9 10]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Create two separate matrices of the same size. Then combine these two matrices row-wise and then column-wise to create the respective new matrix and array.

In [19]:
# write code here
matrice1=np.array([[1,2],[2,5]])
matrice2=np.array([[1,3],[4,6]])
row_wise=np.hstack((matrice1,matrice2))
colum_wise=np.vstack((matrice1,matrice2))

print("Column wise=\n") 
print(colum_wise) 
print("\n Rowise combination=\n") 
row_wise

Column wise=

[[1 2]
 [2 5]
 [1 3]
 [4 6]]

 Rowise combination=



array([[1, 2, 1, 3],
       [2, 5, 4, 6]])

Create a 3x3 matrix of random numbers.

Create a 4x4 matrix of zeros and then fill the first row with the numbers [1, 2, 3, 4].

In [24]:
# write code here
arr3=np.random.rand(3,3)
arr4_0=np.zeros((4,4))
print(arr3)
print(arr4_0)
arr4_0[0]=[1,2,3,4]
print(arr4_0)

[[0.59478951 0.47018399 0.92310546]
 [0.11628697 0.29813066 0.63712003]
 [0.2345178  0.91989209 0.37898822]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 2. 3. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Reshape the 1D array of numbers from 1 to 10 into a 2x5 array.

In [25]:
# write code here
arr_10.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Create two 1D arrays of the same length. Stack them vertically and horizontally.

In [36]:
# write code here
ar1=np.arange(1,6)
ar2=np.arange(6,11)
vertical=np.vstack((ar1,ar2))
print("Vertical\n",vertical)
horizontal=np.hstack((ar1,ar2))
print("Horizontal\n",horizontal)

Vertical
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Horizontal
 [ 1  2  3  4  5  6  7  8  9 10]


Extract the second row and third column of a 4x4 matrix.

Change the value of a specific element in this matrix to 100 using indexing.

In [45]:
matrics=np.random.randint(1,10, size=(4,4))
print(matrics)
print(matrics[1,2])


[[6 6 9 1]
 [5 4 1 6]
 [8 7 5 8]
 [1 6 1 6]]
1


In [46]:
# write code here
matrics[3,3]=100
print(matrics)

[[  6   6   9   1]
 [  5   4   1   6]
 [  8   7   5   8]
 [  1   6   1 100]]


Replace all even numbers in the array of numbers from 1 to 10 with 0.

Replace all values greater than 5 in the 4x4 random float array with 0.5.

In [58]:
# write code here
arr1_10=np.arange(1,11)
print(arr1_10)
arr1_10[arr1_10%2==0]=0
print("After  even values replaced with 0\n", arr1_10)
arr4_by_4=np.random.rand(4,4)*10
print(arr4_by_4)
arr4_by_4[arr4_by_4> 5]=0.5
print("After values>5 replaced with 0.5 \n", arr4_by_4)

[ 1  2  3  4  5  6  7  8  9 10]
After  even values replaced with 0
 [1 0 3 0 5 0 7 0 9 0]
[[4.44909536 6.79486197 9.34114896 7.13264627]
 [2.18124794 3.36057281 0.66799086 8.04556053]
 [4.62380165 8.85393786 8.64109165 8.02241444]
 [2.15810035 3.10964938 6.68737425 7.31046062]]
After values>5 replaced with 0.5 
 [[4.44909536 0.5        0.5        0.5       ]
 [2.18124794 3.36057281 0.66799086 0.5       ]
 [4.62380165 0.5        0.5        0.5       ]
 [2.15810035 3.10964938 0.5        0.5       ]]


Add two arrays element-wise.

Multiply two arrays element-wise.

In [61]:
# write code here
arr1=np.array([1,3,5,7])
arr2=np.array([2,4,6,8])
sum=arr1+arr2 
print("sum=\n",sum)
product=arr1*arr2
print("product=\n",product)


sum=
 [ 3  7 11 15]
product=
 [ 2 12 30 56]


Create a function that sums up the numbers in a randomly generated matrix by rows and by columns.

In [64]:
# write code here
def add(row, col):
    
    matrix = np.random.randint(1, 10, size=(row, col))
    
    row_sums = np.sum(matrix, axis=1)
    col_sums = np.sum(matrix, axis=0)
    
    return matrix, row_sums, col_sums

# call the fun
rows = 4
cols = 5
matrix, row_sums, col_sums = add(rows, cols)
print("Generated Matrix\n", matrix, "\nSum by rows\n", row_sums,"\n Sum by columns\n",col_sums)

Generated Matrix
 [[7 3 4 6 1]
 [8 4 1 5 2]
 [9 2 2 9 4]
 [3 8 9 3 3]] 
Sum by rows
 [21 20 26 26] 
 Sum by columns
 [27 17 16 23 10]


Create a function that takes in two matrices and ensures that they can be multiplied, if they can be multiplied, 
multiply them and print the resulting matrix.


In [67]:
# write code here

def multiply_matrices(mat1, mat2):
    
    if mat1.shape[1] == mat2.shape[0]:
        result = np.dot(mat1, mat2)
        print("Resulting Matrix after multiplication:")
        print(result)
    else:
        print("Error: Matrices cannot be multiplied due to incompatible dimensions.")

# Call the function
matrix1 = np.random.randint(1, 10, (3, 4))  
print("matrix1\n",matrix1)
matrix2 = np.random.randint(1, 10, (4, 2))  
print("matrix2\n",matrix2)
multiply_matrices(matrix1, matrix2)
#test for incompatible dimensions
matr1 = np.random.randint(1, 10, (3, 3))  
print("matrix1\n",matrix1)
matr2 = np.random.randint(1, 10, (4, 2))  
print("matrix2\n",matrix2)
multiply_matrices(matr1, matr2)


matrix1
 [[4 4 3 5]
 [7 2 8 7]
 [8 2 7 4]]
matrix2
 [[6 7]
 [6 8]
 [6 1]
 [3 5]]
Resulting Matrix after multiplication:
[[ 81  88]
 [123 108]
 [114  99]]
matrix1
 [[4 4 3 5]
 [7 2 8 7]
 [8 2 7 4]]
matrix2
 [[6 7]
 [6 8]
 [6 1]
 [3 5]]
Error: Matrices cannot be multiplied due to incompatible dimensions.


Find the minimum value of a randomly generated 5x5 matrix with the indices by row and column of where they appear in the matrix.

In [70]:
# write code here

mat5_by_5 = np.random.randint(1, 10, size=(5, 5))

min_index = np.unravel_index(np.argmin(mat5_by_5), mat5_by_5.shape)
min_value = mat5_by_5[min_index]
print("Generated Matrix:")
print(mat5_by_5)

print("\nMinimum Value:", min_value)



Generated Matrix:
[[2 1 7 3 7]
 [3 6 1 8 3]
 [5 1 6 5 8]
 [6 7 9 7 5]
 [8 5 3 6 3]]

Minimum Value: 1
